/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Metadata } from "next";
import "./globals.css";
// import Navbar from "@/components/navbar";
// import { OverlayProvider } from "@/components/overlay-provider";
import localFont from "next/font/local";
import MainLayout from "@/components/MainLayout";
import Providers from "@/provider";
import client from "@/lib/shopify-client";
import MenuLoader from "@/components/MenuLoader";
// import Navbar2 from "@/components/navbar2";

const basis33 = localFont({
  src: "../font/basis33.ttf",
  display: "swap",
  variable: "--font-basis33",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const {data} = await client.request(`query {
    collections(first: 25) {
      edges {
        node {
          handle
          title
        }
      }
    }
  }`);
  const collections = data.collections.edges.map((item: any) => ({
    id: item.node.id,
    handle: item.node.handle,
    title: item.node.title,
  }));
  return (
    <html lang="en">
      <body className={` ${basis33.variable} antialiased bg-gray-300`}>
        {/* <Navbar /> */}
        {/* <Navbar2 /> */}
        {/* <OverlayProvider>{children}</OverlayProvider> */}
        <MenuLoader collections={collections} />
        <Providers><MainLayout>{children}</MainLayout></Providers>
        
      </body>
    </html>
  );
}
